/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface StencilMessageComposer {}
}

declare global {


  interface HTMLStencilMessageComposerElement extends Components.StencilMessageComposer, HTMLStencilElement {}
  var HTMLStencilMessageComposerElement: {
    prototype: HTMLStencilMessageComposerElement;
    new (): HTMLStencilMessageComposerElement;
  };
  interface HTMLElementTagNameMap {
    'stencil-message-composer': HTMLStencilMessageComposerElement;
  }
}

declare namespace LocalJSX {
  interface StencilMessageComposer extends JSXBase.HTMLAttributes<HTMLStencilMessageComposerElement> {
    'onMessageComposed'?: (event: CustomEvent<string>) => void;
  }

  interface IntrinsicElements {
    'stencil-message-composer': StencilMessageComposer;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


